// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7mHFWf-wRne-051AdCVFGRHKqq8z1JHg',
    appId: '1:544547748529:web:c621e0e2a5a81e91900090',
    messagingSenderId: '544547748529',
    projectId: 'ecommerce-app-403c5',
    authDomain: 'ecommerce-app-403c5.firebaseapp.com',
    storageBucket: 'ecommerce-app-403c5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD00u0Xydlf36u4AQLR9Qt-F-U9BGTEuU8',
    appId: '1:544547748529:android:bb932ed0bec38b7f900090',
    messagingSenderId: '544547748529',
    projectId: 'ecommerce-app-403c5',
    storageBucket: 'ecommerce-app-403c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4sxJbO6XuCcubHNPt5zXqXDL-LClAKM4',
    appId: '1:544547748529:ios:a2a9f8c2bb3b260e900090',
    messagingSenderId: '544547748529',
    projectId: 'ecommerce-app-403c5',
    storageBucket: 'ecommerce-app-403c5.appspot.com',
    androidClientId: '544547748529-jerjn5mskn4namqpr2mm4jk1atiqg522.apps.googleusercontent.com',
    iosClientId: '544547748529-ko18dgpf7qdsgg0vn7s35cgtvlpvoi8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.afStore',
  );

}// Commit at 2022-03-20 12:45:30
// Commit at 2022-12-28 15:18:10
// Commit at 2023-08-19 18:41:43
// Commit at 2024-07-15 10:17:51
// Random commit
// Random commit
// Random commit
// Random commit
